name: Post Virtual Steps

on:
  watch:
    types: started
  schedule:
    - cron: "0 0,6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Post Steps
        run: python ./main.py
        env:
          USERS: ${{ secrets.USERS }}
          BRAND: ${{ secrets.BRAND }}
          MODEL: ${{ secrets.MODEL }}
          VERSION: ${{ secrets.VERSION }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}